version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_DB=recycling_projet
      - POSTGRES_USER=user_recycling
      - POSTGRES_PASSWORD=24recy00/25
    depends_on:
      - db  # Attendre que PostgreSQL soit prêt avant de démarrer Django

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: recycling_projet
      POSTGRES_USER: user_recycling
      POSTGRES_PASSWORD: 24recy00/25
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
