

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      POSTGRES_DB: recyclage11
      POSTGRES_USER: ameur1111
      POSTGRES_PASSWORD: loulou11
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_INITDB_DATABASE: co2calculator
    depends_on:
      - db
      - mongo

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: recyclage11
      POSTGRES_USER: ameur1111
      POSTGRES_PASSWORD: loulou11
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: co2calculator
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
