version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'
      POSTGRES_DB: recyclage
      POSTGRES_USER: ameur11
      POSTGRES_PASSWORD: loulou
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: recyclage
      POSTGRES_USER: ameur11
      POSTGRES_PASSWORD: loulou
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
